pipeline {
    agent any
    // options {
    //     skipStagesAfterUnstable()
    // }
      stages {
        stage('Echo hello world') {
            when {
                branch 'master'
            }
    
            steps {
                echo 'hello world22asdasd2'
            }
        }
    }
    //     stage('Build') {
    //         steps {
    //             sh 'mvn -B -DskipTests clean package'
    //         }
    //     }
    //     stage('Test') {
    //         steps {
    //             sh 'mvn test'
    //         }
    //         post {
    //             always {
    //                 junit 'target/surefire-reports/*.xml'
    //             }
    //         }
    //     }
    //     stage('Deliver') { 
    //         steps {
    //             sh './jenkins/scripts/deliver.sh' 
    //         }
    //     }
    // }
}
